sudo: false
language: node_js
node_js:
  - '10'

cache:
  directories:
    - vendor/bundle
    - node_modules
 
install:
- npm install
script:
- npx now --token $NOW_TOKEN
- npx now alias --token $NOW_TOKEN
  
# branch whitelist
branches:
  only:
  - production