sudo: false
language: node_js
node_js:
  - '10'

cache:
  directories:
    - vendor/bundle
    - node_modules
 
install:
- npm install
script:
- npx gulp
- cp now.json dist/
after_success:
- (cd dist/ && npx now --token $NOW_TOKEN)
- (cd dist/ && npx now alias --token $NOW_TOKEN)
  
# branch whitelist
branches:
  only:
  - production