sudo: false
language: node_js
node_js:
  - '6'

cache:
  directories:
    - vendor/bundle
    - node_modules
 
deploy:
  provider: gae
  keyfile: qrsnapper-d4b905ab556f.json
  project: qrsnapper
  on: production
  skip_cleanup: true

before_install:
  - pip install PyOpenSSL --user
  - openssl aes-256-cbc -K $encrypted_61236829dce9_key -iv $encrypted_61236829dce9_iv -in qrsnapper-d4b905ab556f.json.enc -out qrsnapper-d4b905ab556f.json -d
  - npm install --global gulp && npm install
  
env:
  global:
  - PROJECT_ID=qrsnapper
  - SRV_ACCOUNT=deploy@qrsnapper.iam.gserviceaccount.com
  
# branch whitelist
branches:
  only:
  - production
  - slow
  
# Work out the deployment to app engine.

script:
  - gulp

notifications:
  webhooks: https://webpush.rocks/send-raw?processor=travis&id=https://fcm.googleapis.com/fcm/send/cC8zEklLFpQ:APA91bE7HDYW0TC_FOOavRO1feULYpzo317iidDUKrdVu0AYdtM0WBIi1z0sUBpkIdfv1lEtttzACObOPIg2xpZ0nYBbu7to0t_mh5fDIpg5LzEM2a4ymEB7xo3ER3b5wkxvLoBEN5Gi
